### ISSUE TITLE
xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by satyakam7** [hadim/pytrackmate#2]
I tried to run pytrackmate on a fake xml file as well on the xml file I exported from Fiji and it show the follow error.
<img width="995" alt="Screenshot 2021-07-02 at 6 40 37 AM" src="https://user-images.githubusercontent.com/44098427/124206172-6a9ba400-db00-11eb-9b30-f02f2a3a2493.png">

@hadim

**Comment by hadim** [comment]
Sorry but I am not developing, either maintaining this lib anymore. Maybe the bug is due to an incompatible API of the XML module in the stdlib?

I am happy to have a look at aPR if you can find a fix.

**Comment by satyakam7** [comment]
I have created a Pull request for the correct working on the Py3.9. Fixed.

**Comment by hadim** [comment]
I have released 1.3.0 with your fix. Now on pypi and soon on conda-forge.
